apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels: 
    {{- if .Values.deployment.labels }}
{{ toYaml .Values.deployment.labels | indent 4}}
    {{- end }}
    app: {{ .Chart.Name }}
    tags.datadoghq.com/env: {{ .Values.environment }}
    tags.datadoghq.com/service: {{ .Chart.Name }}
    tags.datadoghq.com/version: {{ .Chart.Version }}
    admission.datadoghq.com/enabled: "true"
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels: 
        {{- if .Values.containers.labels }}
{{ toYaml .Values.containers.labels | indent 8 }}
        {{- end }}
        app: {{ .Chart.Name }}
        tags.datadoghq.com/env: {{ .Values.environment }}
        tags.datadoghq.com/service: {{ .Chart.Name }}
        tags.datadoghq.com/version: {{ .Chart.Version }}
      annotations:
        {{- if .Values.containers.annotations }}
{{ toYaml .Values.containers.annotations | indent 8 }}
        {{- end }}
        admission.datadoghq.com/python-lib.version: v1.20.1
    spec:
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets.secret }}
      containers:
      - name: {{ .Chart.Name }}
        image: ghcr.io/phantomsloth-io/discord-bot:{{ .Values.containers.image.version | default .Chart.Version }}
        imagePullPolicy: {{ .Values.imagePullPolicy | default "IfNotPresent" }}
        {{- with .Values.containers.secrets }}
        envFrom:
          {{- toYaml . | nindent 8 }}
        {{- end }}
        env:
        - name: DD_PROFILING_ENABLED
          value: {{ .Values.datadog.profiling | default "false" | quote }}
        - name: DD_LOGS_INJECTION
          value: {{ .Values.datadog.logInjection | default "false" | quote }}
        - name: DD_APPSEC_ENABLED
          value: {{ .Values.datadog.appSec | default "false" | quote }}
        {{- if .Values.datadog.agentHost.enabled }}
        - name: DD_AGENT_HOST
          valueFrom: 
            fieldRef:
              apiVersion:
                fieldPath: {{ .Values.datadog.agentHost.ip | default "status.hostIP" }}
        {{- end }}

