environment: production

deployment:
  labels: []
  annotations: []
  
containers:
  labels: []
  annotations: []
  
  image: {}
  
  secrets:
  - secretRef: 
      name: discord-secret
      optional: 'False'
  - secretRef: 
      name: nasa-secret
      optional: 'False'
  - secretRef: 
      name: plex-secret
      optional: 'False'

replicas: 1

imagePullPolicy: Always

imagePullSecrets:
  secret: dockerconfigjson-github-com

datadog:
  profiling: true
  logInjection: true
  appSec: true
  agentHost: 
    enabled: true