deployment:
  labels: []
  annotations: {}
containers:
  labels: []
  annotations: {}
  secrets:
  - secretRef: 
      name: discord-secret
  - secretRef: 
      name: nasa-secret
  - secretRef: 
      name: plex-secret

replicas: 1

image:
  name: ghcr.io/phantomsloth-io/discord-bot

imagePullPolicy: Always

imagePullSecrets:
  secret: dockerconfigjson-github-com

datadog:
  labels:
    env: production
